// eslint-disable-next-line camelcase
import { Inter } from 'next/font/google'
import React from 'react'
import '../globals.css'
import UnauthenticatedPageLayout from '@/smarthome/features/session/components/UnauthenticatedPageLayout'

const font = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
    return (
        <html lang="en">
            <body className={font.className}>
                <UnauthenticatedPageLayout>
                    {children}
                </UnauthenticatedPageLayout>
            </body>
        </html>
    )
}
