version: '3'
services:
  smarthome-db:
    container_name: smarthome-db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=smarthome_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=s3cret
    ports:
      - '5432:5432'
    volumes: 
      - ./database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local